#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const publicDir = path.join(projectRoot, 'public');
const indexPath = path.join(publicDir, 'index.html');
const configPath = path.join(publicDir, 'master-config.js');
const checkOnly = process.argv.includes('--check');

const MASTER_PATTERN = /^A-SPEC CODELISTS Version (\d+)\.(\d+)\.(\d+) MASTER WIP - (\d{8})\.xlsx$/i;

function fail(message) {
  console.error(`Master sync failed: ${message}`);
  process.exit(1);
}

function parseDate(dateText, fileName) {
  const year = Number(dateText.slice(0, 4));
  const month = Number(dateText.slice(4, 6));
  const day = Number(dateText.slice(6, 8));
  const date = new Date(Date.UTC(year, month - 1, day));

  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    fail(`invalid YYYYMMDD date in "${fileName}"`);
  }

  return date;
}

function compareMasters(a, b) {
  if (a.date.getTime() !== b.date.getTime()) {
    return b.date.getTime() - a.date.getTime();
  }

  for (let i = 0; i < 3; i += 1) {
    if (a.versionParts[i] !== b.versionParts[i]) {
      return b.versionParts[i] - a.versionParts[i];
    }
  }

  return a.fileName.localeCompare(b.fileName);
}

if (!fs.existsSync(publicDir)) fail(`public folder not found: ${publicDir}`);
if (!fs.existsSync(indexPath)) fail(`index.html not found: ${indexPath}`);

const masters = fs.readdirSync(publicDir, { withFileTypes: true })
  .filter(entry => entry.isFile())
  .map(entry => {
    const match = entry.name.match(MASTER_PATTERN);
    if (!match) return null;

    const versionParts = match.slice(1, 4).map(Number);
    const dateText = match[4];
    return {
      fileName: entry.name,
      version: versionParts.join('.'),
      versionParts,
      dateText,
      date: parseDate(dateText, entry.name)
    };
  })
  .filter(Boolean)
  .sort(compareMasters);

if (masters.length === 0) {
  fail('no matching master workbook was found in public/. Expected: A-SPEC CODELISTS Version x.y.z MASTER WIP - YYYYMMDD.xlsx');
}

const selected = masters[0];
const html = fs.readFileSync(indexPath, 'utf8');
const htmlChecks = [
  ['a master-config.js script tag', /<script\s+src=["']master-config\.js["']><\/script>/],
  ['MASTER_CONFIG sourced from window.ASPEC_MASTER_CONFIG', /window\.ASPEC_MASTER_CONFIG/],
  ['MASTER_FILE_URL sourced from MASTER_CONFIG.fileName', /const MASTER_FILE_URL\s*=\s*MASTER_CONFIG\.fileName\s*;/],
  ['MASTER_FILE_NAME sourced from MASTER_CONFIG.fileName', /const MASTER_FILE_NAME\s*=\s*MASTER_CONFIG\.fileName\s*;/]
];

for (const [description, pattern] of htmlChecks) {
  if (!pattern.test(html)) fail(`index.html is missing ${description}`);
}

if (/A-SPEC CODELISTS Version \d+\.\d+\.\d+ MASTER WIP - \d{8}\.xlsx/i.test(html)) {
  fail('index.html contains a hardcoded master workbook filename');
}

const config = `/* AUTO-GENERATED by scripts/sync-master.js during build. DO NOT EDIT. */\n` +
  `window.ASPEC_MASTER_CONFIG = Object.freeze(${JSON.stringify({
  fileName: selected.fileName,
  version: selected.version,
  date: `${selected.dateText.slice(0, 4)}-${selected.dateText.slice(4, 6)}-${selected.dateText.slice(6, 8)}`,
  dateRaw: selected.dateText
}, null, 2)});\n`;

if (checkOnly) {
  if (!fs.existsSync(configPath) || fs.readFileSync(configPath, 'utf8') !== config) {
    fail('master-config.js is missing or out of date. Run npm run sync-master.');
  }

  console.log(`Master sync check passed: ${selected.fileName}`);
  process.exit(0);
}

fs.writeFileSync(configPath, config, 'utf8');
console.log(`Generated public/master-config.js: Version ${selected.version}, date ${selected.dateText}`);
console.log('public/index.html remains unchanged and contains no hardcoded master filename.');

if (masters.length > 1) {
  console.log(`Found ${masters.length} matching master files; selected the latest by date, then version.`);
}
